management.info.env.enabled=true
server.port = 8585
server.servlet.context-path=/workintech

info.app.name=WorkintechS17
info.app.description=Tax
info.app.version=1.0.0
management.endpoints.web.exposure.include=info,health,mappings
